apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: consul-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/zooeymoon1989/consul-up-and-running.git
    targetRevision: HEAD
    path: chapter4/dev
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true