apiVersion: consul.hashicorp.com/v1alpha1 
kind: ServiceIntentions
metadata:
  name: frontend
  namespace: consul 
spec:
  destination:
    name: "frontend"
  sources:
    - name: "ingress-gateway"
      action: allow
      permissions:
        - http:
            pathPrefix: /admin
          action: deny
        - http:
            pathPrefix: /
          action: allow
