apiVersion: consul.hashicorp.com/v1alpha1 
kind: ServiceIntentions
metadata:
  name: frontend
spec:
  destination:
    name: frontend
  sources:
    - name: ingress-gateway
      permissions:
        - http:
            pathPrefix: /admin
          action: deny
        - http:
            pathPrefix: /
          action: allow
    - name: ingress-gateway-2
      permissions:
        - http:
            pathPrefix: /admin
          action: deny
        - http:
            pathPrefix: /
          action: allow
