apiVersion: consul.hashicorp.com/v1alpha1
kind: IngressGateway
metadata:
  name: ingress-gateway
  namespace: consul
spec:
  listeners: 
    - port: 30310
      protocol: http
      services:
        - name: frontend
          hosts: ["liwenqiang.site","localhost","127.0.0.1"]