apiVersion: consul.hashicorp.com/v1alpha1
kind: IngressGateway
metadata:
  name: ingress-gateway
  namespace: consul
spec:
  listeners: 
    - port: 8080
      protocol: http
      services:
        - name: frontend
          hosts: ["birdwatch.liwenqiang.site"]
    # - port: 8080
    #   protocol: http
    #   services:
    #     - name: hello-svc
    #       hosts: ["hello-svc.liwenqiang.site"]
    # - port: 3000
    #   protocol: http
    #   services:
    #     - name: grafana
    #       hosts: ["grafana.liwenqiang.site"]