apiVersion: consul.hashicorp.com/v1alpha1
kind: IngressGateway
metadata:
  name: ingress-gateway
  namespace: consul
spec:
  listeners: 
    - port: 8080
      protocol: http
      services:
        - name: frontend
          hosts: ["birdwatch.liwenqiang.site"]
    - port: 8500
      protocol: http
      services:
        - name: consul-ui
          hosts: ["consul.liwenqiang.site"]