apiVersion: consul.hashicorp.com/v1alpha1
kind: IngressGateway
metadata:
  name: ingress-gateway
  namespace: consul
spec:
  listeners: 
    - port: 8080
      protocol: http
      services:
        - name: frontend
          hosts: ["liwenqiang.site","localhost","127.0.0.1"]
      externalIPs:
        - 129.226.216.230
        - 43.156.118.232
        - 43.156.122.2