apiVersion: consul.hashicorp.com/v1alpha1
kind: IngressGateway
metadata:
  name: ingress-gateway
  namespace: consul
spec:
  listeners: 
    - port: 80
      protocol: http
      services:
        - name: frontend
          hosts: ["liwenqiang.site","localhost"]