apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: backend-v2 
  labels:
    app: backend 
spec:
  replicas: 3 
  selector:
    matchLabels: 
      app: backend
      version: v2
  template:
    metadata: 
      labels:
        app: backend
        version: v2
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/service-meta-version: "v2"
    spec: 
      containers:
        - name: backend
          image: ghcr.io/consul-up/birdwatcher-backend:1.0.0 
          env:
            - name: BIND_ADDR 
              value: "0.0.0.0:7000"
            - name: TRACING_URL
              value: "http://172.22.16.8:9411"
          ports:
          - containerPort: 7000
          readinessProbe:
            httpGet:
              port: 7000
              path: /healthz
            periodSeconds: 5